name = "transcript-tax-monitor-pro-api"
main = "src/index.js"
compatibility_date = "2026-03-06"

routes = [
  { pattern = "transcript.taxmonitor.pro/api/*", zone_name = "taxmonitor.pro" },
  { pattern = "transcript.taxmonitor.pro/forms/transcript/*", zone_name = "taxmonitor.pro" },
  { pattern = "transcript.taxmonitor.pro/transcript/*", zone_name = "taxmonitor.pro" },
  { pattern = "transcript.taxmonitor.pro/v1/*", zone_name = "taxmonitor.pro" }
]

[observability.logs]
enabled = true

[[durable_objects.bindings]]
class_name = "TokenLedger"
name = "TOKEN_LEDGER"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TokenLedger"]

[[kv_namespaces]]
binding = "KV_TRANSCRIPT"
id = "cf03ea6f9e934bd59d301192352f0489"
preview_id = "cf03ea6f9e934bd59d301192352f0489"

[[r2_buckets]]
binding = "R2_TRANSCRIPT"
bucket_name = "transcript-taxmonitor-pro"

[vars]
CREDIT_MAP_JSON = "{\"price_1T83KXQEa4WBi79g8sD2NI7c\":10,\"price_1T84hAQEa4WBi79gCziLGXUD\":25,\"price_1T8pDtQEa4WBi79gWfSQwLgM\":100}"
GOOGLE_CLIENT_EMAIL = "tax-monitor-worker@tax-monitor-pro.iam.gserviceaccount.com"
GOOGLE_TOKEN_URI = "https://oauth2.googleapis.com/token"
GOOGLE_WORKSPACE_USER_INFO = "info@taxmonitor.pro"
GOOGLE_WORKSPACE_USER_NOREPLY = "no-reply@taxmonitor.pro"
GOOGLE_WORKSPACE_USER_SUPPORT = "support@taxmonitor.pro"
PRICE_10 = "price_1T83KXQEa4WBi79g8sD2NI7c"
PRICE_100 = "price_1T8pDtQEa4WBi79gWfSQwLgM"
PRICE_25 = "price_1T84hAQEa4WBi79gCziLGXUD"
TRANSCRIPT_RETURN_ORIGINS_JSON = "[\"https://transcript.taxmonitor.pro\"]"

# Secrets (set using `wrangler secret put`)
# GOOGLE_PRIVATE_KEY
# STRIPE_SECRET_KEY
# STRIPE_WEBHOOK_SECRET
